In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

In [17]:
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

In [19]:
from scripts.pipeline import extract, load, transform, run_pipeline

In [27]:
# Step 1: Extract raw data
df = extract()  # loads CSV from config.json
print("Raw data preview:")
display(df.head())

Loading raw data from: C:\Users\kusha\documents\shankar\data/customer_churn_dataset.csv
Raw data preview:

,customer_id,tenure,monthly_charges,total_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,1,52,54.20,2818.40,Month-to-month,Credit,DSL,No,Yes,1,No
1,2,15,35.28,529.20,Month-to-month,Debit,DSL,No,No,2,No
2,3,72,78.24,5633.28,Month-to-month,Debit,DSL,No,No,0,No
3,4,61,80.24,4894.64,One year,Cash,Fiber,Yes,Yes,0,No
4,5,21,39.38,826.98,Month-to-month,UPI,Fiber,No,No,4,Yes

In [29]:
# Step 2: Transform data
# ------------------------------
df_clean = transform(df)
print("Cleaned data preview:")
display(df_clean.head())

Transforming data: dropping duplicates and missing values
Cleaned data preview:

,customer_id,tenure,monthly_charges,total_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,1,52,54.20,2818.40,Month-to-month,Credit,DSL,No,Yes,1,No
1,2,15,35.28,529.20,Month-to-month,Debit,DSL,No,No,2,No
2,3,72,78.24,5633.28,Month-to-month,Debit,DSL,No,No,0,No
3,4,61,80.24,4894.64,One year,Cash,Fiber,Yes,Yes,0,No
4,5,21,39.38,826.98,Month-to-month,UPI,Fiber,No,No,4,Yes

In [31]:
df.isna().sum()

customer_id            0
tenure                 0
monthly_charges        0
total_charges          0
contract               0
payment_method         0
internet_service    2013
tech_support           0
online_security        0
support_calls          0
churn                  0
dtype: int64

In [33]:
df_clean.isna().sum()

customer_id         0
tenure              0
monthly_charges     0
total_charges       0
contract            0
payment_method      0
internet_service    0
tech_support        0
online_security     0
support_calls       0
churn               0
dtype: int64

In [35]:
df.shape

(20000, 11)

In [37]:
df_clean.shape

(17987, 11)

In [39]:
# Step 3: Load cleaned data
# ------------------------------
load(df_clean)  # saves to CSV path in config.json

Saved cleaned data to: C:\Users\kusha\documents\shankar\data/clean_customer_data.csv

In [41]:
# Step 4: Run full pipeline in one step (optional)
# ------------------------------
run_pipeline()  # uncomment to run full ETL automatically

Loading raw data from: C:\Users\kusha\documents\shankar\data/customer_churn_dataset.csv
Transforming data: dropping duplicates and missing values
Saved cleaned data to: C:\Users\kusha\documents\shankar\data/clean_customer_data.csv
Pipeline complete!